application: hw1web101
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: helloworld.app

- url: /unit2/rot13
  script: rot13.app

- url: /unit2/signup
  script: signup.app

- url: /unit2/welcome
  script: signup.app
